// Generated by view binder compiler. Do not edit!
package com.michael.foody.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.motion.widget.MotionLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.michael.foody.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentOverviewBinding implements ViewBinding {
  @NonNull
  private final MotionLayout rootView;

  @NonNull
  public final ImageView cheapImageView;

  @NonNull
  public final TextView cheapTextView;

  @NonNull
  public final ImageView dairyFreeImageView;

  @NonNull
  public final TextView dairyFreeTextView;

  @NonNull
  public final ImageView glutenFreeImageView;

  @NonNull
  public final TextView glutenFreeTextView;

  @NonNull
  public final View gradientOverlay;

  @NonNull
  public final ImageView healthyImageView;

  @NonNull
  public final TextView healthyTextView;

  @NonNull
  public final ImageView likesImageView;

  @NonNull
  public final TextView likesTextView;

  @NonNull
  public final ImageView mainImageView;

  @NonNull
  public final ScrollView scrollView2;

  @NonNull
  public final TextView summaryTextView;

  @NonNull
  public final ImageView timeImageView;

  @NonNull
  public final TextView timeTextView;

  @NonNull
  public final TextView titleTextView;

  @NonNull
  public final ImageView veganImageView;

  @NonNull
  public final TextView veganTextView;

  @NonNull
  public final ImageView vegetarianImageView;

  @NonNull
  public final TextView vegetarianTextView;

  private FragmentOverviewBinding(@NonNull MotionLayout rootView, @NonNull ImageView cheapImageView,
      @NonNull TextView cheapTextView, @NonNull ImageView dairyFreeImageView,
      @NonNull TextView dairyFreeTextView, @NonNull ImageView glutenFreeImageView,
      @NonNull TextView glutenFreeTextView, @NonNull View gradientOverlay,
      @NonNull ImageView healthyImageView, @NonNull TextView healthyTextView,
      @NonNull ImageView likesImageView, @NonNull TextView likesTextView,
      @NonNull ImageView mainImageView, @NonNull ScrollView scrollView2,
      @NonNull TextView summaryTextView, @NonNull ImageView timeImageView,
      @NonNull TextView timeTextView, @NonNull TextView titleTextView,
      @NonNull ImageView veganImageView, @NonNull TextView veganTextView,
      @NonNull ImageView vegetarianImageView, @NonNull TextView vegetarianTextView) {
    this.rootView = rootView;
    this.cheapImageView = cheapImageView;
    this.cheapTextView = cheapTextView;
    this.dairyFreeImageView = dairyFreeImageView;
    this.dairyFreeTextView = dairyFreeTextView;
    this.glutenFreeImageView = glutenFreeImageView;
    this.glutenFreeTextView = glutenFreeTextView;
    this.gradientOverlay = gradientOverlay;
    this.healthyImageView = healthyImageView;
    this.healthyTextView = healthyTextView;
    this.likesImageView = likesImageView;
    this.likesTextView = likesTextView;
    this.mainImageView = mainImageView;
    this.scrollView2 = scrollView2;
    this.summaryTextView = summaryTextView;
    this.timeImageView = timeImageView;
    this.timeTextView = timeTextView;
    this.titleTextView = titleTextView;
    this.veganImageView = veganImageView;
    this.veganTextView = veganTextView;
    this.vegetarianImageView = vegetarianImageView;
    this.vegetarianTextView = vegetarianTextView;
  }

  @Override
  @NonNull
  public MotionLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentOverviewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentOverviewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_overview, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentOverviewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cheap_imageView;
      ImageView cheapImageView = ViewBindings.findChildViewById(rootView, id);
      if (cheapImageView == null) {
        break missingId;
      }

      id = R.id.cheap_textView;
      TextView cheapTextView = ViewBindings.findChildViewById(rootView, id);
      if (cheapTextView == null) {
        break missingId;
      }

      id = R.id.dairy_free_imageView;
      ImageView dairyFreeImageView = ViewBindings.findChildViewById(rootView, id);
      if (dairyFreeImageView == null) {
        break missingId;
      }

      id = R.id.dairy_free_textView;
      TextView dairyFreeTextView = ViewBindings.findChildViewById(rootView, id);
      if (dairyFreeTextView == null) {
        break missingId;
      }

      id = R.id.gluten_free_imageView;
      ImageView glutenFreeImageView = ViewBindings.findChildViewById(rootView, id);
      if (glutenFreeImageView == null) {
        break missingId;
      }

      id = R.id.gluten_free_textView;
      TextView glutenFreeTextView = ViewBindings.findChildViewById(rootView, id);
      if (glutenFreeTextView == null) {
        break missingId;
      }

      id = R.id.gradient_overlay;
      View gradientOverlay = ViewBindings.findChildViewById(rootView, id);
      if (gradientOverlay == null) {
        break missingId;
      }

      id = R.id.healthy_imageView;
      ImageView healthyImageView = ViewBindings.findChildViewById(rootView, id);
      if (healthyImageView == null) {
        break missingId;
      }

      id = R.id.healthy_textView;
      TextView healthyTextView = ViewBindings.findChildViewById(rootView, id);
      if (healthyTextView == null) {
        break missingId;
      }

      id = R.id.likes_imageView;
      ImageView likesImageView = ViewBindings.findChildViewById(rootView, id);
      if (likesImageView == null) {
        break missingId;
      }

      id = R.id.likes_textView;
      TextView likesTextView = ViewBindings.findChildViewById(rootView, id);
      if (likesTextView == null) {
        break missingId;
      }

      id = R.id.main_imageView;
      ImageView mainImageView = ViewBindings.findChildViewById(rootView, id);
      if (mainImageView == null) {
        break missingId;
      }

      id = R.id.scrollView2;
      ScrollView scrollView2 = ViewBindings.findChildViewById(rootView, id);
      if (scrollView2 == null) {
        break missingId;
      }

      id = R.id.summary_textView;
      TextView summaryTextView = ViewBindings.findChildViewById(rootView, id);
      if (summaryTextView == null) {
        break missingId;
      }

      id = R.id.time_imageView;
      ImageView timeImageView = ViewBindings.findChildViewById(rootView, id);
      if (timeImageView == null) {
        break missingId;
      }

      id = R.id.time_textView;
      TextView timeTextView = ViewBindings.findChildViewById(rootView, id);
      if (timeTextView == null) {
        break missingId;
      }

      id = R.id.title_textView;
      TextView titleTextView = ViewBindings.findChildViewById(rootView, id);
      if (titleTextView == null) {
        break missingId;
      }

      id = R.id.vegan_imageView;
      ImageView veganImageView = ViewBindings.findChildViewById(rootView, id);
      if (veganImageView == null) {
        break missingId;
      }

      id = R.id.vegan_textView;
      TextView veganTextView = ViewBindings.findChildViewById(rootView, id);
      if (veganTextView == null) {
        break missingId;
      }

      id = R.id.vegetarian_imageView;
      ImageView vegetarianImageView = ViewBindings.findChildViewById(rootView, id);
      if (vegetarianImageView == null) {
        break missingId;
      }

      id = R.id.vegetarian_textView;
      TextView vegetarianTextView = ViewBindings.findChildViewById(rootView, id);
      if (vegetarianTextView == null) {
        break missingId;
      }

      return new FragmentOverviewBinding((MotionLayout) rootView, cheapImageView, cheapTextView,
          dairyFreeImageView, dairyFreeTextView, glutenFreeImageView, glutenFreeTextView,
          gradientOverlay, healthyImageView, healthyTextView, likesImageView, likesTextView,
          mainImageView, scrollView2, summaryTextView, timeImageView, timeTextView, titleTextView,
          veganImageView, veganTextView, vegetarianImageView, vegetarianTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
